language: node_js
node_js: "8"

os:
  - linux

install:
  - npm install

script:
  - npm run dist
  - mkdir release
  - zip -j release/tplink-monitor-linux.zip dist/tplink-monitor-linux logger-config.json
  - zip -j release/tplink-monitor-macos.zip dist/tplink-monitor-macos logger-config.json 
  - zip -j release/tplink-monitor-win.zip dist/tplink-monitor-win.exe logger-config.json 

deploy:
  provider: releases
  api_key:
    secure: "Un4XrV5DDJ9LPVYhILWcfiN60UDGQaqZ8WNHUqt9iAOcvXk/bxJZlYQpwgLv588g1om/SDcbNjljGWnruWi+QYrZmvtrkQ06oMn25FXvi4EbrxFiVZEjStpDAld2GkWT+WeftDo6sQvIBl0lEb0xZ2bRSkbPYCwW5ku2ITXTk0W+237GY7OjvyLpmvmMYfSeZpoyyfAQxNEZK6fYUMf/lA/L7nHEw2NdyfXZrUvtESRNkljVc0btaDASEntuMLpCsMZRPXsJIjTCCsW83r183jOv8ZD4S4q66eI64fdF6dq6G8l1pDAXCQFJRU1RAkX5NES+BD/8FfX5yyrOF7H3S5+t6866GWEshz+5hyvsK7TLkQsI0J9stXF470sB4DUF90dg5wZSrfSHNEYC+GQ3NbTSp7lmOtKo97YftVyq746MDSHfeDMiNyxUb+JzCqxQ3iB3/c0yLWlOk63uNMyDu2SEPEta4dIKqGC8J/1jvYM4LfNnRIhtirusQluETuu+LH+TfFtcq++RK5HRcGgpzTmexMYmhTebuDosoRCqonNZiCH/APMHbSf80ShobdNN1BO9Mz+geApf479W3UeUvD5CJXJtHlEm/NwPyq3kqmyjOX9DcqAxg652+MMe3fI6d0a2KAh0hlQObEVMjYD8hoLTA1BIqgJmEGl1/0s7fno="
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true